### ISSUE TITLE
Organization still visible after I leave

### ISSUE THREAD

**Issue by bobziroll** [gitspeak/gitspeak-desktop#18]
I joined a test organization of @perborgen 's to see how GitSpeak could help us at V School give feedback to our student's code. I just left the organization, but since it was selected in GitSpeak, it still showed I had access to issues, casts, etc. from the org, even after refreshing the app. (It disappeared from the dropdown of orgs/repos I could access, but was still the selected org.) Only after navigating to another repo was I unable to get back to the org I removed myself from.

**Comment by perborgen** [comment]
This one has been fixed. Now, you'll loose access when you refresh (just how GitHub does this).
