### ISSUE TITLE
Improve "install" instructions for Linux

### ISSUE THREAD

**Issue by 42pre** [gitspeak/gitspeak-desktop#19]
## Summary

I couldn't find any instructions on how to "install" GitSpeak in Linux. Maybe some rudimentary instructions could be put in the project wiki or the project's README.md?

## Install instructions - proposal

1. Download the latest GitSpeakSetup.AppImage from the [Releases](https://github.com/gitspeak/gitspeak-desktop/releases) tab.
2. Make the AppImage executable with `chmod u+x GitSpeakSetup.AppImage`
3. Run it and you should get a popup asking you if you want to integrate GitSpeak into your system.
4. Read the info text carefully, and then click "Yes". It should then integrate itself nicely into your system.

## Links

*  [AppImage Website](https://appimage.org/)
*  [How To Use AppImage in Linux - Complete Guide](https://itsfoss.com/use-appimage-linux/)

**Comment by scanf** [comment]
I have added it to the wiki, thanks. https://github.com/gitspeak/gitspeak/wiki/Installing-GitSpeak-on-Linux
