### ISSUE TITLE
Possibility to hide menu

### ISSUE THREAD

**Issue by jancborchardt** [gitspeak/gitspeak-desktop#21]
On GNOME / Ubuntu at least the menu shows permanently (assume it’s not an issue with macOS top menus):
![gitspeak menu](https://user-images.githubusercontent.com/925062/58174700-c6976b80-7c9e-11e9-9d0f-e12a29a3edb4.png)

Would be really cool if either the menu is hideable or doesn’t show by default, as it takes a full row.

**Comment by somebee** [comment]
See gitspeak/gitspeak#391

**Comment by somebee** [comment]
Maybe you could look into this @scanf? Should be a simple config option I think. See electron docs

**Comment by scanf** [comment]
Sure, can look at it this weekend.
