### ISSUE TITLE
Sandbox issues on Debian

### ISSUE THREAD

**Issue by MarkoShiva** [gitspeak/gitspeak-desktop#29]
It fails with error:
```
:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_GitSpeyQdhE5/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```

If i run it with option --no-sandbox it starts but that is not the way that app should work.

**Comment by in1t3r** [comment]
adding kernel parameter 
``` # sysctl -w kernel.unprivileged_userns_clone=1 ```
actually makes app run.

**Comment by scanf** [comment]
Do you know what is required to get it to work under the sandbox? I mean without changing kernel parameters or bypassing the sanbdox.  I am not familiar with SUID sandbox development. 



We are focused on the macOS version but patches very welcome 😄 I can look into this when I get some free time.



Thanks.

**Comment by MarkoShiva** [comment]
I do not use that app. I just tried.

**Comment by MarkoShiva** [comment]
it works on the archlinux after running:
```
npm install
npm start
```
however I dont find app that much useful as I use web interface for issues.
So I'll close the issue.
